### ISSUE TITLE
legit can't even open your .msi

### ISSUE THREAD

**Issue by DaddyKami** [XFG16/YouTubeDiscordPresence#10]
what more do i have to say, everything even windows itself is trying its hardest to prevent you from opening this?

**Comment by XFG16** [comment]
Can you send a screenshot of the message you get when you double click the MSI installer?

**Comment by DaddyKami** [comment]
[https://ibb.co/fGJbsqS](url)

this installation package could not be opened. Have the application vendor verify that this is a valid Windows installer package.
several warning for trojan aswell btw
even when you FORCE it to open i get this and windows denies the installation

**Comment by XFG16** [comment]
I'm sorry, but I wasn't able to reproduce your issue. It's most likely something on your client, such as a corrupted Windows system or another app disrupting the installation. The installation package is not at fault if you downloaded from [here](**[url](https://github.com/XFG16/YouTubeDiscordPresence/releases/tag/1.4.2)**) because it has been working for every other user.

I've attached a possible thread that could help solve your problem, but the MSI installer is not the root cause here.

https://www.makeuseof.com/installation-package-could-not-be-opened-error-windows/

In addition, the warnings you are getting for the trojans are false positives. The most likely reason they are showing is because I currently don't have the ability to sign the files I distribute due to hefty costs.
