### ISSUE TITLE
Warning Trojan Virus message?

### ISSUE THREAD

**Issue by Areos-Hotah** [XFG16/YouTubeDiscordPresence#12]
Warning Trojan Virus message?  Why?

**Comment by XFG16** [comment]
Hello! You can safely ignore the message. In this case, whatever you're using to detect it showing something known as a **false positive.** The reason why the application is triggering the message is because I currently don't have the funds to sign the file. As such, even though it isn't a virus, some scanners automatically flag it as one if it isn't signed.
