### ISSUE TITLE
Show album covers using YouTube Music

### ISSUE THREAD

**Issue by SeA-luby** [XFG16/YouTubeDiscordPresence#4]
Hello, here are two features I'm eagerly looking forward to for this project.
- It would be really cool to see the album cover instead of the YouTube Music icon.
- When listening to YouTube music, all channel names end with '- Topic'. I would like this phrase to be removed.

**Comment by XFG16** [comment]
Hey there SeA-luby!

Regarding your first point, that's something that I am unable to do. The reason for this is because any assets used as the icon for the rich presence must be uploaded and cached on Discord, for which there is a limited number of pictures available. In other words, it would be impossible to cover every single album cover for each artist. Discord does not allow for external internet sources (i.e. images from YouTube Music) to be displayed on the rich presence.

I can however add a feature to deal with your second point though! You can expect an update in the near future that addresses your point.

Thanks for taking the time to share your thoughts!

**Comment by SeA-luby** [comment]
I don't know how rich presence and this program works, but there is a way in the popular CustomRP app to specify a custom image via web links. The following is how I display a specific image in rich presence using [an image link](https://lh3.googleusercontent.com/nbRTHBa0NkqoYmWBAyNe_sP-yqQwOm9NqMrEY-ZANoDokJXMZ7Jao5OtZVPRsMmusbLR4PsP1BiZAoIr=w544-h544-l90-rj) in CustomRP:

![image](https://user-images.githubusercontent.com/89302673/216800929-91f2295b-28ab-4efa-b0f6-bea55b89e119.png)

Wouldn't it be possible to apply such a function through a similar method? Thank you for your efforts.

**Comment by XFG16** [comment]
You're exactly right!

In fact, I was tricked up by the documentation of the library I implemented, but you can indeed do something with external images. Originally, I believed that external image sources couldn't be used by the rich presence.

Thanks for the heads up! I'll see if I can implement your feature in the next update.

Stay tuned!

**Comment by XFG16** [comment]
Something along the lines of this...?

<table>
  <tr>
    <td valign="left"><img src="https://user-images.githubusercontent.com/55029965/216802344-524d0c77-1499-4d0d-b859-1baca73981ee.png"/></td>
    <td valign="right"><img src="https://user-images.githubusercontent.com/55029965/216802386-8be21717-9cd8-422f-8149-4e30bce9790b.png"/></td>
  </tr>
</table>

**Comment by SeA-luby** [comment]
Yes, that looks great!

**Comment by XFG16** [comment]
Great!

I'll roll this out as a feature in the next update as soon as I have time.

Thank you for your time and contributions

**Comment by XFG16** [comment]
Hello! Just wanted to check in with you now that the update is out. Is everything working fine on your end after installing the new version?

**Comment by SeA-luby** [comment]
Everything works fine! Thank you <3
![image](https://user-images.githubusercontent.com/89302673/218027957-6f6646ae-7cd8-41cf-89b1-6b5550ff0481.png)
